title: 전민지가 만든 github 블로그
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://https://minzyjeon.github.io/

aux_links:
  Template Repository: https://github.com/minzyjeon/minzyjeon.github.io
  
plugins:
  - jekyll-default-layout

logo: "/assets/images/avatar.png"

favicon_ico: "/assets/images/favicon.ico"